[tool.poetry]
name = "rides-minimal"
version = "0.1.0"
description = "Analyse GPS tracks"
authors = ["E Pogrebnyak <e.pogrebnyak@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
