# -*- coding: utf-8 -*-
"""rides_minimal_v4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_C-fdRLY1EMGcQlLEhg065IhT4hsBPp

# Запуск поиска сходимости
"""

#!pip install -U git+https://github.com/epogrebnyak/rides-minimal.git

RAW_DATA_URL = (
    "https://dl.dropboxusercontent.com"
    "/sh/hibzl6fkzukltk9/AABTFmhvDvxyQdUaBsKl4h59a"
    "/data_samples_json.zip"
)

RAW_DATA_URL_UPDATED = (
    "https://dl.dropboxusercontent.com"
    "/sh/hibzl6fkzukltk9/AABSMicBJlwMnlmA3ljt1uY5a"
    "/data_samples-json2.zip")

DAYS = ["2020-05-21"]
TYPES = ["freight"]
DATA_FOLDER = "data2"

from rider import Segments, Increment
SEARCH_PARAM = dict(
    simplify_with=Segments.by_distance(n=10),
    search_radius_1=10,
    refine_with=Increment.by_distance(step_km=2.5),
    search_radius_2=2.5 * 1.2,
)

import rider
df_full, df_summaries = rider.get_dataset(RAW_DATA_URL_UPDATED, DATA_FOLDER)
subset_df = rider.make_subset(df_full, df_summaries, DAYS, TYPES)
(trip_df, pairs_df), _abc = rider.results(subset_df, 
                                          df_summaries, 
                                          search_param=SEARCH_PARAM)
trip_df.to_csv("trips.csv")
pairs_df.head(20).to_csv("top20pairs.csv",index=False)

df_full.query("date == '2020-05-20'")
df_summaries

pairs_df

"""# Анализ сходимости"""

pairs_df.plot.scatter(x='max_dist', y='len', alpha = 0.5)

import matplotlib.pyplot as plt
pairs_df.plot.scatter(x='cov', y='op', alpha = 0.5)
plt.axhline(0.75,c='red')

pairs_df.plot.scatter(x='len', y='op', alpha = 0.5)
plt.axvline(420)
plt.axvline(180)
plt.axhline(0.75)

pairs_df[(pairs_df.op > 0.75) & (pairs_df.len > 400)]

from rider.plotting import plot_two
from rider.routes import distance_increment
trips, routes, milages = _abc
plot_two(routes, 37, 12, distance_increment(5))

trip_df.loc[[37,12],:]

plot_two(routes, 0, 23, distance_increment(1))

trip_df.loc[[0,23],:]

pairs_df[pairs_df.id_1.isin([0, 23]) & pairs_df.id_2.isin([0, 23])]

pairs_df.plot.scatter(x='max_dist', y='op', alpha = 0.5)
plt.axvline(80,c='red')
plt.axvline(20,c='red')
plt.axhline(0.75,c='red')

pairs_df.max_dist.hist(bins=40)

trip_df.km.hist()

pairs_df.plot.scatter(x='cov_1',y='cov_2', alpha=0.5)